"""change DiscogsInstance primary key to bigint

Revision ID: da564425fbbe
Revises: b96bd65a7506
Create Date: 2026-06-11 08:28:09.601829

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'da564425fbbe'
down_revision = 'b96bd65a7506'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.execute('ALTER TABLE discogs_instance_discogs_release DROP CONSTRAINT discogs_instance_discogs_release_ibfk_1')
    #op.execute('ALTER TABLE unit DROP CONSTRAINT unit_ibfk_2')
    with op.batch_alter_table('discogs_instance', schema=None) as batch_op:
        batch_op.alter_column('instance_id',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    with op.batch_alter_table('discogs_instance_discogs_release', schema=None) as batch_op:
        batch_op.alter_column('instance_id',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.BigInteger())
    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.alter_column('discogs_instance_id',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.BigInteger())
    op.create_foreign_key('discogs_instance_discogs_release_ibfk_1', 'discogs_instance_discogs_release', 'discogs_instance', ['instance_id'], ['instance_id'], ondelete='CASCADE')
    op.create_foreign_key('unit_ibfk_2', 'unit', 'discogs_instance', ['discogs_instance_id'], ['instance_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discogs_instance', schema=None) as batch_op:
        batch_op.alter_column('instance_id',
               existing_type=sa.BigInteger(),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###
